In [ ]:
# Why do we use KNN ? 
# This is used for classification problem , recommandtion system , pattern reconiztion 
# Ex: movie recommandation , customer segementation , diesease prediction

# What is KNN ? 
# Knn Works using similiraty of the data 

# How KNN works ? 
# We select n values as the hyperparameter and find those many values similier to the data
# step 1 : Chose K value 
# Step 2 : select K class
# Step 3 : Check majority class
# Step 4 : acessend these classes

# KNN depends upon distace 
# 1 .  Eucliden Distance  -> Continuous numerical data
# 2 .  Manhattan Distance -> Grid based dist 
# 3 . Minkwshi Distance  -> Genralized dist
# 4 . Hamming Distance -> Binary Categorical
# etc 

Eucliden Distance : sqrt( (x2-x1)^2 + (y2-y1)^2 )

In [5]:
import math 

x1 = 2
x2 = 3

y2 = 6
y1 = 7

dist = math.sqrt( (x2-x1)**2 + (y2-y1)**2 )
print(dist)

1.4142135623730951

In [13]:
from sklearn.datasets import load_iris

irs = load_iris()

In [14]:
import pandas as pd
import numpy as np

In [20]:
df = pd.DataFrame(data = irs.data ,  columns=irs.feature_names)

In [21]:
df['target'] = irs.target

In [22]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [23]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [24]:
df.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)      target
count         150.000000        150.000000         150.000000        150.000000  150.000000
mean            5.843333          3.057333           3.758000          1.199333    1.000000
std             0.828066          0.435866           1.765298          0.762238    0.819232
min             4.300000          2.000000           1.000000          0.100000    0.000000
25%             5.100000          2.800000           1.600000          0.300000    0.000000
50%             5.800000          3.000000           4.350000          1.300000    1.000000
75%             6.400000          3.300000           5.100000          1.800000    2.000000
max             7.900000          4.400000           6.900000          2.500000    2.000000

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [38]:
def model(df):
    X = df.iloc[: , :-1]
    y = df.iloc[: , -1]
    X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2)
    sc = StandardScaler()
    X_train_scaled = sc.fit_transform(X_train)
    X_test_scaled = sc.transform (X_test)
    lg = KNeighborsClassifier(n_neighbors=5 , metric='manhattan')
    lg.fit(X_train , y_train)
    lg_preds = lg.predict(X_test)
    print(classification_report(y_test , lg_preds))
    cm = confusion_matrix(y_test , lg_preds)
    print(cm)

In [55]:
model(df)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.91      1.00      0.95        10
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

[[11  0  0]
 [ 0 10  0]
 [ 0  1  8]]