In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("Data.csv")
df.head()

   Feature1  Feature2  Feature3  Feature4  Target
0        63        59      1164        -3      39
1        89        54       977        -2      54
2        73        46       725        -1      88
3        25        52       921         0      70
4        60        60      1222         0      91

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Feature1  10000 non-null  int64
 1   Feature2  10000 non-null  int64
 2   Feature3  10000 non-null  int64
 3   Feature4  10000 non-null  int64
 4   Target    10000 non-null  int64
dtypes: int64(5)
memory usage: 390.8 KB

In [4]:
df.describe()

           Feature1     Feature2      Feature3      Feature4        Target
count  10000.000000  10000.00000  10000.000000  10000.000000  10000.000000
mean      49.677800     54.42060   1026.990600     -0.492900     64.575000
std       23.182306      8.66951    315.410128      1.706763     20.202366
min       10.000000     40.00000    531.000000     -3.000000     30.000000
25%       29.000000     47.00000    748.000000     -2.000000     47.000000
50%       50.000000     54.00000    999.000000      0.000000     65.000000
75%       70.000000     62.00000   1294.000000      1.000000     82.000000
max       89.000000     69.00000   1618.000000      2.000000     99.000000

In [5]:
df.shape

(10000, 5)

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import classification_report,confusion_matrix,r2_score

In [16]:
def model(df):
    X = df.iloc[: , :-1]
    y = df.iloc[: , -1]
    X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2)
    sc = StandardScaler()
    X_train_scaled = sc.fit_transform(X_train)
    X_test_scaled = sc.transform (X_test)
    lg = SVR(epsilon=1.0 , C=1.0 , kernel='linear')
    lg.fit(X_train , y_train)
    lg_preds = lg.predict(X_test)
    # print(classification_report(y_test , lg_preds))
    # cm = confusion_matrix(y_test , lg_preds)
    # print(cm)
    print(r2_score(y_test,lg_preds))

In [17]:
model(df)

0.07357701396090077